### ISSUE TITLE
Simple Captcha not rendering in grails 2.5.5

### ISSUE THREAD

**Issue by jkramerDev** [domurtag/grails-simple-captcha#17]
Hey there, 

Thanks for building this.  I've just performed an upgrade from grails 1.x to 2.5.5 & in two different apps the simple captcha is not rendering where it worked previously.   Notable is a 403 permission error on browser network debug.  Thanks for your consideration.

**Comment by domurtag** [comment]
It's no possible for me to investigate your issue without instructions to reproduce it or (ideally) a sample app that reproduces it. I'm closing this issue until you can provide one of these.

By the way, I'm using this plugin in a Grails 2.5.4 app, so it's not simply the case that it's incompatible with Grails 2.5.X

**Comment by jkramerDev** [comment]
Fair enough, Thanks for the quick response.

**Comment by donalmurtagh** [comment]
I might know what your problem is: if you've upgraded from the spring-security 1.X plugin to 2.X, the simple-captcha URLs will have been changed from publicly accessible to secured. To fix this, you'll need to add rules to `Config.groovy` to change them back to publicly accessible.

**Comment by domurtag** [comment]
I might know what your problem is: if you've upgraded from the spring-security 1.X plugin to 2.X, the simple-captcha URLs will have been changed from publicly accessible to secured. To fix this, you'll need to add rules to Config.groovy to change them back to publicly accessible.

**Comment by jkramerDev** [comment]
Right as rain – adding this to config.groovy fixed it:

grails.plugin.springsecurity.controllerAnnotations.staticRules = [
       '/simplecaptcha/captcha/**': ['IS_AUTHENTICATED_FULLY']
]

Sorry, obviously it had nothing to do with the plugin after all.

cheers
