### ISSUE TITLE
captcha letters don't seem to be verified

### ISSUE THREAD

**Issue by gus6177** [domurtag/grails-simple-captcha#7]
I installed the simple captcha, but when I submit the page with an incorrect captcha the page saves anyway.

This is the code in my gsp.
````gsp
<div class="text-center">					
<img src="${createLink(controller: 'simpleCaptcha', action: 'captcha')}"/>
<div><label class="text-center" for="captcha">Type the letters above in the box below:</label></div>
<g:textField name="captcha"/>				
</div>	
````
this is the code in the controller for the gsp page.

````groovy
def simpleCaptchaService  

// This is the action that handles the submission of the form with the CAPTCHA
def save = {
 boolean captchaValid = simpleCaptchaService.validateCaptcha(params.captcha)
}	
````

Has anyone had the same issue?

**Comment by domurtag** [comment]
In the example action you've shown above you're stored the result of the CAPTCHA in a variable, but you also need an if-statement (or similar) that does something different when the CAPTCHA is correct/incorrect, e.g.

def save = {
  boolean captchaValid = simpleCaptchaService.validateCaptcha(params.captcha)

  if (captchaValid) {
    // do this when the CAPTCHA is correct
  } else {
    // do this when the CAPTCHA is incorrect
  }
} 

Here's [an example](https://github.com/domurtag/festivals/blob/master/grails-app/controllers/ie/festivals/security/RegisterController.groovy#L35L53)

**Comment by gus6177** [comment]
So something like this?

def save = {
boolean captchaValid = simpleCaptchaService.validateCaptcha(params.captcha)

 if (captchaValid) {
respond "Captcha is Correct"
       }

else {
respond "Please try again"
 return
}
}

**Comment by domurtag** [comment]
Maybe....I can't tell you if the code above will do what you want because you haven't told me anything about your application. Specifically, I don't know what you want to do when the CAPTCHA is valid/invalid

**Comment by domurtag** [comment]
Feel free to post further comments if you want more help, but I've closed this issue, because it's not really a question/problem concerning the plugin itself

**Comment by gus6177** [comment]
All :I relay want to do is submit the page if the capatcha is correct and if it’s not then tell them letters are invalid.

Here is the gsp portion.

<div class="text-center">
                                 <img src="${createLink(controller: 'simpleCaptcha', action: 'captcha')}"/>
                                 <div><label class="text-center" for="captcha">Type the letters above in the box below:</label></div>
                                 <g:textField name="captcha"/>
                                 </div>

                                 <fieldset class="buttons">
                                        <div class="text-center">
                                               <g:actionSubmit action="save"
                                                     value="${message(code: 'default.button.generate.label', default: 'Submit')}"
              onclick="return confirm('${message(code: 'default.button.generate.confirm.message', default: 'Please verify the information you provided is accurate. Click “Cancel” to review or “OK” to submit"')}');" />
                                        </div>

                                        <g:hiddenField name="pageId" value="non_create" />

                                 </fieldset>

**Comment by domurtag** [comment]
> All :I relay want to do is submit the page if the capatcha is correct and if it’s not then tell them letters are invalid.

It sounds like you want to detect on the client-side (in the browser) if the CAPTCHA is correct and prevent the form/page submission if it's not. This isn't supported, you can only determine whether the CAPTCHA is correct on the server-side. So the usual workflow is to detect on the server-side the CAPTCHA status and render/redirect to a different depending on whether it's correct/incorrect, or alternatively add the CAPTCHA status to the view model and implement different behaviour in the GSP itself. Have a look at the example I linked to above, the app itself is deployed on http://festivals.ie

**Comment by gus6177** [comment]
Sorry to bug you, I was researching this some more and was wondering if this simple captcha was capable of audio?

**Comment by domurtag** [comment]
> Sorry to bug you, I was researching this some more and was wondering if this simple captcha was capable of audio?

no
